# Generated by Django 5.0.6 on 2024-07-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Causas', '0002_alter_causa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='image',
            field=models.ImageField(upload_to='Causas/Media'),
        ),
    ]
